### ISSUE TITLE
Can't access extension

### ISSUE THREAD

**Issue by HeleenE** [PhillippOhlandt/bolt-extension-user-profiles#1]
When I try to access the extension through the menu option I get the following error: 

No route found for "GET /bolt/profile/extended"

Any ideas why this could be happening? 

Thanks in advance, 
Heleen

**Comment by PhillippOhlandt** [comment]
Hey,

sorry for the late answer, I got no notification from github.

Can you tell me more about your setup? Is `/bolt` your admin url or have you changed it? And what's your Bolt version?

**Comment by HeleenE** [comment]
Hi, 

Not sure if this is still relevant, but my setup was /admin for the admin and the version is Bolt 2.2.16.

Sorry for the slow response.

**Comment by PhillippOhlandt** [comment]
@HeleenE Hey, is it still relevant?

**Comment by HeleenE** [comment]
@PhillippOhlandt I'm still having this issue yes, but there's no rush.

(as you can clearly see by my slow responses, sorry!)

**Comment by PhillippOhlandt** [comment]
Well, I really don't know whats happening there. Could you try to debug it?

**Comment by PhillippOhlandt** [comment]
I am closing this for now. If the problem still exists and you have some more details, feel free to re-open.
